dm820: Remove fastboot from RDEPENDS
Fastboot is compatible with dm7080 only.
New OE-core breaks his legs about it.

ERROR: Nothing RPROVIDES 'fastboot' (but /home/hains/openvision-development-platform/meta-dream/
recipes-bsp/recovery/recovery_1.1.bb RDEPENDS on or otherwise requires it)
fastboot was skipped: incompatible with machine dm820 (not in COMPATIBLE_MACHINE)